#!/opt/perl5/bin/perl

use strict;
use warnings;

my $basepath = shift;

opendir (my $dir, $basepath) or die "Cannot open $basepath: $!";
my @libs;

while (my $dist = readdir $dir) {
    if (-d "$basepath/$dist/lib") {
        push @libs, "$basepath/$dist/lib";
    }
}

print '$PERL5LIB="$PERL5LIB:', $_, '; export $PERL5LIB;', "\n" for @libs;
