package OpusVL::FB11::Model::AppKitAuthDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'OpusVL::FB11::Schema::AppKitAuthDB',
    
    connect_info => {
        dsn => 'dbi:SQLite:./t/lib/auto/TestApp/root/db/appkit_auth.db',
        user => '',
        password => '',
    }
);

=head1 NAME

OpusVL::FB11::Model::AppKitAuthDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<OpusVL::FB11>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<OpusVL::FB11::Schema::AppKitAuthDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

Benjamin Martin,1,07720061678,0722061678

=head1 COPYRIGHT and LICENSE

Copyright (C) 2010 OpusVL

This software is licensed according to the "IP Assignment Schedule" provided with the development project.

=cut

1;
