package OpusVL::FB11::Model::FB11AuthDB;

use Moose;
use OpusVL::FB11::Hive;
extends 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'OpusVL::FB11::Schema::FB11AuthDB',
    traits => 'SchemaProxy'
);

after BUILD => sub {
    my $self = shift;
    OpusVL::FB11::Hive->register_brain($self->schema);
};

=head1 NAME

OpusVL::FB11::Model::FB11AuthDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<OpusVL::FB11>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<OpusVL::FB11::Schema::FB11AuthDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.38

=head1 AUTHOR

Benjamin Martin,1,07720061678,0722061678

=head1 COPYRIGHT and LICENSE

Copyright (C) 2010 OpusVL

This software is licensed according to the "IP Assignment Schedule" provided with the development project.

=cut

1;
